Add card results
Niweera/cinesimile pull request #51
Opened 2020-10-17 11:42 UTC by MilePaor

2020-10-17 11:42 UTC, Niweera commented
Hey @MilePaor, thank you for creating this pull request! Have a wonderful day...

2020-10-17 15:21 UTC, Niweera requested changes
Please address the issues mentioned.

2020-10-17 15:21 UTC, Niweera commented on src/components/SearchBox/index.js
> +            <h4 id={x.id} onClick={() => setSelectedMovie(x)}>
Please add a key to the element.

2020-10-17 15:21 UTC, Niweera commented on src/components/SearchBox/index.js
> +              <MovieCard
Please add a key to the element.

2020-10-19 09:01 UTC, Niweera commented
Hi @MilePaor,
if the above issues are not addressed within the next 48 hrs, we will close this pull request.

2020-10-19 18:54 UTC, MilePaor commented
@Niweera please check now.

2020-10-19 18:58 UTC, Niweera approved these changes

2020-10-19 18:58 UTC, merged